name: sidebarx
description: flutter multiplatform navigation sidebar / side navigationbar / drawer widget
version: 0.16.3
homepage: https://github.com/Frezyx/sidebarx
repository: https://github.com/Frezyx/sidebarx

topics:
  - widget
  - ui
  - drawer
  - navigation
  - sidebar

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
